### ISSUE TITLE
The name 'context' does not exist

### ISSUE THREAD

**Issue by redowl3** [AnkitSharma-007/BlazorGrid#3]
Hi, 

I'm getting an error The name 'context' does not exist when using the grid   

 <GridRow>
            <td>@context.Date.ToShortDateString()</td>
            <td>@context.TemperatureC</td>
            <td>@context.TemperatureF</td>
            <td>@context.Summary</td>
        </GridRow>

**Comment by AnkitSharma-007** [comment]
Take a look at this. 

https://github.com/aspnet/AspNetCore/issues/9642

**Comment by redowl3** [comment]
thanks
