### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by nic0l45** [AnkitSharma-007/BlazorGrid#4]
![image](https://user-images.githubusercontent.com/48603062/57532511-d069b800-7309-11e9-9075-e6a26a8737f8.png)
![image](https://user-images.githubusercontent.com/48603062/57532576-e7100f00-7309-11e9-9ad5-7bfb973fc44e.png)

**Comment by michaelccote** [comment]
The Http error is normal in my opinion. You need to to connect your own data or provide a HTTP service like in the original template. 

The context error is a bug though. You would need to add the projet to the solution, reference this projet from your client for it to compile. You probably tried the same thing that I tried by simply adding the NuGet Package and adding the @using in the _Imports.razor doccument.

**Comment by AnkitSharma-007** [comment]
This is a bug with VS 19. Take a look at bug #3

**Comment by dolare1** [comment]
I am using Visual Studio Enterprise 2019 Preview v. 16.3.0 Preview 1.0 and I am still getting compile time error for "The name context does not exist in the current context"

Do I need to add the project to solution, and reference it to compile?
